// src/gl/scenes/field.ts — scene `field`: the record on the home hero (spec §6.1). DATA: one point per
// default-branch commit (all of them, in every tier; k = 1), on 19 repo lanes along a broken time axis.
//
// The anchor (HeroField's [data-gl-scene="field"]) overhangs the plot band by PAD so records sliding along a
// lane or drifting up on scroll are never cut by the scissor; HeroField.astro sets the same insets in CSS.
// Handles (motion/intro.ts, motion/sections/hero.ts): set('uScan' | 'uScroll' | 'uPicked', v), pick(x, y),
// step(dir). Defaults: uScan 1.1 (lit: repeat visits and the no-intro path), uScroll 0, uPicked -1.
// Look: gen/glimmer.ts FIELD_LOOK (one soft gaussian glimmer per record; /posters/field.svg draws the same).

import type { Frame, RecordRef, SceneDef, StepDir, Tier } from '../types';
import { program, POINT_FRAG, type Program } from '../core/program';
import VERT from '../shaders/field.vert?raw';
import { LANES, ROWS, shaHex } from '../gen/lanes';
import { FIELD_LOOK, SIGMA } from '../gen/glimmer';
import {
  clearLive,
  decode,
  newBand,
  PICK_R,
  PickGrid,
  setLive,
  stepFrom,
  type Band,
  type FieldData,
} from './inspect';

/** Anchor overhang around the plot band, CSS px (= HeroField.astro `.field-anchor` insets). */
export const PAD = { x: 16, top: 32, bottom: 8 } as const;

interface ManifestEntry {
  url: string;
  count?: number;
  mode?: 'time' | 'ordinal';
}

// The manifest is generated by scripts/pack-commits.mjs (prebuild); a glob tolerates its absence (poster stays).
const MANIFEST = Object.values(
  import.meta.glob<Record<string, ManifestEntry>>('../../data/gl-manifest.json', { eager: true, import: 'default' }),
)[0];

type Loc = WebGLUniformLocation | null;
interface Locs {
  band: Loc;
  view: Loc;
  laneH: Loc;
  dpr: Loc;
  time: Loc;
  scan: Loc;
  scroll: Loc;
  halo: Loc;
  picked: Loc;
  look: Loc;
  pointer: Loc;
  holes: Loc;
  holeCount: Loc;
  pulse: Loc;
  fg: Loc;
  glim: Loc;
}

interface State {
  prog: Program;
  locs: Locs | null;
  vao: WebGLVertexArrayObject | null;
  buf: WebGLBuffer | null;
  data: FieldData;
  count: number;
  band: Band;
  grid: PickGrid;
  /** keyboard cursor (last picked / stepped record) */
  cursor: number;
}

function num(v: number | number[] | undefined, fallback: number): number {
  return typeof v === 'number' && Number.isFinite(v) ? v : fallback;
}

function lookup(p: Program): Locs {
  const u = (n: string): Loc => p.loc(n);
  return {
    band: u('uBand'),
    view: u('uView'),
    laneH: u('uLaneH'),
    dpr: u('uDpr'),
    time: u('uTime'),
    scan: u('uScan'),
    scroll: u('uScroll'),
    halo: u('uHalo'),
    picked: u('uPicked'),
    look: u('uLook'),
    pointer: u('uPointer'),
    holes: u('uHoles'),
    holeCount: u('uHoleCount'),
    pulse: u('uPulse'),
    fg: u('uFg'),
    glim: u('uGlim'),
  };
}

function ref(s: State, i: number): RecordRef | null {
  if (i < 0 || i >= s.count) return null;
  const lane = s.data.lane[i] as number;
  const L = LANES[lane] as (typeof LANES)[number];
  // label = the sha7 (the repo name on the ordinal axis); the page builds the readout and the link
  return { index: i, lane, label: s.data.mode === 'time' ? shaHex(s.data.sha[i] as number) : L.repo };
}

const def: SceneDef<FieldData> = {
  id: 'field',
  kind: 'DATA',

  async load(src: string, _tier: Tier): Promise<FieldData> {
    const entry = MANIFEST?.[src];
    if (!entry?.url) throw new Error(`[field] no manifest entry "${src}"`);
    const res = await fetch(entry.url);
    if (!res.ok) throw new Error(`[field] ${entry.url}: ${res.status}`);
    return decode(await res.arrayBuffer());
  },

  create(gl: WebGL2RenderingContext, data: FieldData): State {
    const prog = program(gl, 'field', VERT, POINT_FRAG);
    // interleaved: aX, aY, aSeed, aLatest
    const n = data.count;
    const arr = new Float32Array(n * 4);
    for (let i = 0; i < n; i++) {
      const o = i * 4;
      arr[o] = data.x[i] as number;
      arr[o + 1] = data.y[i] as number;
      arr[o + 2] = data.sx[i] as number;
      arr[o + 3] = data.latest[i] as number;
    }
    const vao = gl.createVertexArray();
    const buf = gl.createBuffer();
    gl.bindVertexArray(vao);
    gl.bindBuffer(gl.ARRAY_BUFFER, buf);
    gl.bufferData(gl.ARRAY_BUFFER, arr, gl.STATIC_DRAW);
    // layout(location = 0..3) in field.vert: aX, aY, aSeed, aLatest
    for (let a = 0; a < 4; a++) {
      gl.enableVertexAttribArray(a);
      gl.vertexAttribPointer(a, 1, gl.FLOAT, false, 16, a * 4);
    }
    gl.bindVertexArray(null);
    gl.bindBuffer(gl.ARRAY_BUFFER, null);
    const s: State = {
      prog,
      locs: null,
      vao,
      buf,
      data,
      count: n,
      band: newBand(),
      grid: new PickGrid(),
      cursor: -1,
    };
    setLive(data, s.grid, s.band);
    return s;
  },

  resize(state: unknown, rect: DOMRectReadOnly): void {
    const s = state as State;
    const b = s.band;
    b.x = PAD.x;
    b.y = PAD.top;
    b.w = Math.max(0, rect.width - 2 * PAD.x);
    b.h = Math.max(0, rect.height - PAD.top - PAD.bottom);
    b.laneH = b.h / ROWS;
    s.grid.build(s.data, b);
    setLive(s.data, s.grid, b);
  },

  set(state: unknown, name: string, v: number | number[]): void {
    const s = state as State;
    if (name === 'uPicked' && typeof v === 'number' && v >= 0 && v < s.count) s.cursor = Math.round(v);
  },

  draw(gl: WebGL2RenderingContext, state: unknown, f: Frame): boolean {
    const s = state as State;
    if (!s.prog.ready()) return true;
    const p = s.prog;
    const L = s.locs ?? (s.locs = lookup(p));
    const b = s.band;
    const P = f.params;
    gl.useProgram(p.glp);
    gl.uniform4f(L.band, b.x, b.y, b.w, b.h);
    gl.uniform2f(L.view, f.view[0], f.view[1]);
    gl.uniform1f(L.laneH, b.laneH);
    gl.uniform1f(L.dpr, f.dpr);
    gl.uniform1f(L.time, f.reduced ? 0 : f.t);
    gl.uniform1f(L.scan, num(P.uScan, 1.1));
    gl.uniform1f(L.scroll, num(P.uScroll, 0));
    gl.uniform1f(L.halo, f.halo);
    gl.uniform1f(L.picked, num(P.uPicked, -1));
    const size = f.tier === 'full' ? FIELD_LOOK.size.full : FIELD_LOOK.size.lite;
    gl.uniform4f(L.look, size, FIELD_LOOK.peak, SIGMA, FIELD_LOOK.latest);
    gl.uniform3f(L.pointer, f.pointer[0], f.pointer[1], f.pointer[2]);
    gl.uniform4fv(L.holes, f.holes);
    gl.uniform1i(L.holeCount, f.holeCount);
    gl.uniform4f(L.pulse, f.pulse[0], f.pulse[1], f.pulse[2], f.pulse[3]);
    gl.uniform3f(L.fg, f.fg[0], f.fg[1], f.fg[2]);
    gl.uniform3f(L.glim, f.glim[0], f.glim[1], f.glim[2]);
    gl.bindVertexArray(s.vao);
    gl.drawArrays(gl.POINTS, 0, s.count);
    gl.bindVertexArray(null);
    return true; // records twinkle (the engine idles lite at 30 fps and draws reduced motion on change only)
  },

  pick(state: unknown, x: number, y: number): RecordRef | null {
    const s = state as State;
    return ref(s, s.grid.nearest(x, y, PICK_R));
  },

  step(state: unknown, dir: StepDir): RecordRef | null {
    const s = state as State;
    const i = stepFrom(s.data, s.cursor, dir);
    if (i >= 0) s.cursor = i;
    return ref(s, i);
  },

  count(state: unknown): number {
    return (state as State).count;
  },

  destroy(gl: WebGL2RenderingContext, state: unknown): void {
    const s = state as State;
    if (s.vao) gl.deleteVertexArray(s.vao);
    if (s.buf) gl.deleteBuffer(s.buf);
    s.vao = null;
    s.buf = null;
    clearLive(s.data);
  },
};

export default def;
